# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cache.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61\x63he.proto\x12\x05\x63\x61\x63he\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1c\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\r\n\x0bSetResponse2g\n\x05\x43\x61\x63he\x12.\n\x03Get\x12\x11.cache.GetRequest\x1a\x12.cache.GetResponse\"\x00\x12.\n\x03Set\x12\x11.cache.SetRequest\x1a\x12.cache.SetResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETREQUEST']._serialized_start=22
  _globals['_GETREQUEST']._serialized_end=47
  _globals['_GETRESPONSE']._serialized_start=49
  _globals['_GETRESPONSE']._serialized_end=77
  _globals['_SETREQUEST']._serialized_start=79
  _globals['_SETREQUEST']._serialized_end=119
  _globals['_SETRESPONSE']._serialized_start=121
  _globals['_SETRESPONSE']._serialized_end=134
  _globals['_CACHE']._serialized_start=136
  _globals['_CACHE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
